### PR TITLE
Added axum support through an optional feature

### PR DESCRIPTION
**Pull request by PaulDotSH**
Added to "fix" the request https://github.com/rust-sailfish/sailfish/issues/139

I think the documentation could be improved for my code and help would be welcome, since I don't know how to make it better myself.
This doesn't break any functionality but I'm not sure what tests I can even add, or how to, so again, help would be welcome.

This is some sample code, to see how the API looks like
```rs
#[derive(TemplateOnce)]
#[template(path = "test.stpl")]
struct TestTemplate<'a> {
    s: &'a str
}

async fn endpoint_1() -> impl IntoResponse {
    AxumTemplate::from(TestTemplate { s: "test" }).with_custom_error_message("<html><b>Foo</b></html>".to_string())
}

async fn endpoint_2() -> impl IntoResponse {
    AxumTemplate::from(TestTemplate { s: "test" })
}
```

@vthg2themax

### CODE REVIEW

**Comment by vthg2themax** [comment]
@PaulDotSH This looks great! The documentation is kinda setup strange, it's built with a python script by the GitHub workflow process, so it's in a separate repo that I gotta remember how it works again to get this part added. I should probably add this to the readme for next time I need to update the docs. I'm good with merging these changes, they look good. I just need some time this weekend or so to test it out, and then I'll merge it into the main project. Thank you for your contribution!

**Comment by vthg2themax** [comment]
@PaulDotSH I am looking into this, but it looks like perhaps there is some confusion as to what this library does. This library only does parsing, and does not support adding in http handling requests. Your contribution appears to me (please correct me if I am mistaken) to expand the bounds of this project to support Axum. This would conflict with people who choose to use other http handlers such as `actix-http`. Perhaps you could create a sailfish-axum crate which would provide the sort of glue to make that process easier? If I am not seeing this correctly, feel free to include more details about what an example usage of this would be such as including a sort of dummy program layout that uses this new `AxumTemplate`, and the `test.stpl` file so that we could see how we could use this contribution.

**Comment by vthg2themax** [comment]
We had a request a little while back which allowed minfying the output along with JavaScript, but it was dropped because we weren't sure how it would affect people who use this library to do templating for things like documentation files, or other non-web uses. Perhaps we could make this project support more use cases such as different optional http handlers, but I am not sure if that would add too much confusion as to the responsibilities of what this library should do.

**Comment by PaulDotSH** [comment]
@vthg2themax Sure, sorry for the confusion, this adds an optional "feature" to support Axum, the code isn't compiled unless you add the said feature (axum_support). This doesn't limit the use of any other library, but just gets rid of some boilerplate. Instead of having something like
```rust
    let ctx = PickChoiceTemplate {
        fs_classes: &classes[0..split_idx],
        ss_classes: &classes[split_idx..],
        choices,
    };

    let body = ctx.render_once().map_err(|e| AppError(e.into()))?;

    Ok(Html::from(body))
```

You could just have

```
    Ok(AxumTemplate::from(PickChoiceTemplate {
        fs_classes: &classes[0..split_idx],
        ss_classes: &classes[split_idx..],
        choices,
    }))
```

I understand if you think this feature is out of scope, however it was requested in https://github.com/rust-sailfish/sailfish/issues/139 and you commented on it saying it would've been helpful, but if you think something else is more appropriate, I don't see any problem with changing the code.

**Comment by PaulDotSH** [comment]
> We had a request a little while back which allowed minfying the output along with JavaScript, but it was dropped because we weren't sure how it would affect people who use this library to do templating for things like documentation files, or other non-web uses. Perhaps we could make this project support more use cases such as different optional http handlers, but I am not sure if that would add too much confusion as to the responsibilities of what this library should do.

If you think minifying would be a good addition, I could add that as another feature, having it as another feature and maybe as a derive macro, being called "minify" or something, but that would be entirely something else imo

**Comment by vthg2themax** [comment]
> @vthg2themax Sure, sorry for the confusion, this adds an optional "feature" to support Axum, the code isn't compiled unless you add the said feature (axum_support). This doesn't limit the use of any other library, but just gets rid of some boilerplate. Instead of having something like
> 
> ```rust
>     let ctx = PickChoiceTemplate {
>         fs_classes: &classes[0..split_idx],
>         ss_classes: &classes[split_idx..],
>         choices,
>     };
> 
>     let body = ctx.render_once().map_err(|e| AppError(e.into()))?;
> 
>     Ok(Html::from(body))
> ```
> 
> You could just have
> 
> ```rust
>     Ok(AxumTemplate::from(PickChoiceTemplate {
>         fs_classes: &classes[0..split_idx],
>         ss_classes: &classes[split_idx..],
>         choices,
>     }))
> ```
> 
> I understand if you think this feature is out of scope, however it was requested in #139 and you commented on it saying it would've been helpful, but if you think something else is more appropriate, I don't see any problem with changing the code.

I thought about this some more, and I think what you have is great, however I am having some doubts now about trying to add this new dependency, and then having to ensure I maintain it in the future. I can't promise I will have more time in the future to make sure that I do a great job keeping the axum dependency up to date, and because I am not using it directly, I don't believe I would be the best person to be in charge of ensuring that tests and documentation for it are maintained. I think the idea you have is very solid, and would make an excellent crate that could then rely upon Sailfish, but as of right now, I believe it is in the best interest of this project to not merge this change. Thank you for your interest, and I apologize for not thinking through the change from #139 before I commented on it.

**Pull request closed without merging**
