### PR TITLE
Require fields to be accessed using `self` and introduce `TemplateMut` and `Template`.

### PR DESCRIPTION
**Pull request by yaoxi-std**
By requiring fields to be accessed using `self` in templates, it becomes possible to call a method on `self`. I really need this feature in my project. For more information, see [this issue](https://github.com/rust-sailfish/sailfish/issues/72).

This change also enables the implementation of the `Template` trait. I've also introduced `TemplateMut` and `Template`, which allows templates to be rendered multiple times and be modified while rendering (e.g., for caching purposes). Below are the definitions of these traits:

```rust
pub trait TemplateOnce: Sized {
  fn render_once(self) -> RenderResult;
  fn render_once_to(self, buf: &mut Buffer) -> Result<(), RenderError>;
}

pub trait TemplateMut: TemplateOnce {
  fn render_mut(&mut self) -> RenderResult;
  fn render_mut_to(&mut self, buf: &mut Buffer) -> Result<(), RenderError>;
}

pub trait Template: TemplateMut {
  fn render(&self) -> RenderResult;
  fn render_to(&self, buf: &mut Buffer) -> Result<(), RenderError>;
}
```

The differences between these traits are similar to those in `FnOnce`, `FnMut` and `Fn`.

Tests for calling methods are copied from [here](https://github.com/Svenskunganka/sailfish/commit/03c3e425fccdc17363c1f0d7658ccd4ffd8438a3).

Some documentation may need further adjustments.

### CODE REVIEW

**Comment by yaoxi-std** [comment]
Any response to this PR?

Is this crate still being maintained?

**Comment by vthg2themax** [comment]
Sorry dude, I've been on holiday. I hope to have this reviewed in the next week. Thank you for your interest!

As always, please let me know if you have any comments, questions, or concerns! 

Thanks, 
Vince Pike 
989.397.8548 


-------- Original Message --------

**Comment by vthg2themax** [comment]
@yaoxi-std I have uploaded a new version named: 0.8.4-beta.2 to crates.io.
After doing that however, and running my own project that uses sailfish, it appears that this breaks my application. The error messages I get are something along the lines of:
```
error[E0425]: cannot find value `component_name` in this scope
 --> /home/vince/Nextcloud/Projects/sandusky-library-site/target/debug/build/sailfish-compiler-918910bb88e1d0e3/out/templates/7746bbdc1e5b934d-b0f1ba41ab9b4a39:4:40
  |
4 |     __sf_rt::render_escaped!(__sf_buf, component_name);
  |                                        ^^^^^^^^^^^^^^
  |
help: you might have meant to use the available field
  |
4 |     __sf_rt::render_escaped!(__sf_buf, self.component_name);
  |                                        +++++
```
I assume this is because I am using the TemplateOnce attribute, as many of the previous users of this library are also doing. This would cause a great many users to have to refactor their code to handle this change just to retain previous functionality. Do you think there is perhaps a way forward to allow us to retain backwards compatibility?

**Comment by yaoxi-std** [comment]
@vthg2themax Sorry for the late reply.

After reading your comment, I've found two ways to maintain compatibility.

One approach is to add a new trait, like `TemplateSimple`, which consumes `self` and functions the same way as the original `TemplateOnce`. Users would only need to replace `TemplateOnce` with `TemplateSimple`, instead of adding `self.` in their template files.

The other approach is to introduce a new attribute, such as `#[template(keep_self = true)]`, to be used alongside `#[derive(TemplateOnce)]`. This attribute would enable the new feature and be set to `false` by default. It could also be adjusted through global configurations, allowing users to retain their existing code without modifications.

Users of this crate might prefer the second approach, although it may require more time to implement. However, I believe the migration cost of the first approach is also acceptable. What do you think?

**Comment by vthg2themax** [comment]
@yaoxi-std I think the best path forward for users of this library would be the second option that allows code from before to continue working without additional needed modifications to existing code. I can update the documentation once I see the tests, and everything compiles and looks good. I appreciate the extra effort that this would take, but think that it would be well worth the time for other users of this project, and very much appreciated.

**Comment by vthg2themax** [comment]
@yaoxi-std Before you get going too much with the change, I thought about it some more, and your first option sounds good along with documentation updates about this change, and us signifying this is a breaking change. I think clogging up the attributes would make readability worse, and the following idea you had would make it clear that the template we are using is for a simple case. What do you think?
```
One approach is to add a new trait, like TemplateSimple, which consumes self and functions the same way as the original TemplateOnce. Users would only need to replace TemplateOnce with TemplateSimple, instead of adding self. in their template files.
```

**Comment by yaoxi-std** [comment]
> @yaoxi-std Before you get going too much with the change, I thought about it some more, and your first option sounds good along with documentation updates about this change, and us signifying this is a breaking change. I think clogging up the attributes would make readability worse, and the following idea you had would make it clear that the template we are using is for a simple case. What do you think?
> 
> ```
> One approach is to add a new trait, like TemplateSimple, which consumes self and functions the same way as the original TemplateOnce. Users would only need to replace TemplateOnce with TemplateSimple, instead of adding self. in their template files.
> ```

Good, I think. I will implement the first approach these days.

**Comment by yaoxi-std** [comment]
@vthg2themax I think the code has been completed now and all those tests have passed. This pull request is ready-to-merge once the documents are modified to fit the updated code.

**Comment by vthg2themax** [comment]
@yaoxi-std I will have time this weekend to create a beta version, test, and update the documentation site. Thank you for your contribution!

**Comment by vthg2themax** [comment]
@yaoxi-std The change has been committed to a beta version as follows:
https://crates.io/crates/sailfish/0.9.0-beta
I'm going to leave it there for a week or so to see if anyone finds any unexpected breaking changes, and then will promote it, in addition to updating any missing documentation pieces I find needing done.

**Comment by vthg2themax** [comment]
@yaoxi-std Your changes have been integrated, and pushed to the main branch.

**Pull request closed without merging**
